// APSC 142 Engineering Programming Project Starter Code
// Copyright Sean Kauffman 2024

// This code is written for you to simplify the process of changing the colours of
// your console text. The code in here is beyond the scope of this course.

// *** DO NOT EDIT THIS FILE ***

#ifndef PROJECT_COLOURS_H
#define PROJECT_COLOURS_H

#define YELLOW 6
#define PINK 13
#define BLUE 1
#define WHITE 15

/**
 * Get a single character from the console, without waiting for the user to press enter.
 * This function should work from any desktop operating system.
 * The function blocks until a character is entered.
 * @return a single character pressed by the user
 */
#if defined (__APPLE__) || defined (__linux__)
char getch(void);
#endif
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
#include <conio.h>
#endif

/**
 * Change the colour of the following text!
 * Everyone, even Windows, supports ANSI colours now.
 * @param colour a colour as defined in colours.h
 * @return 0 on success, 1 on failure
 */
int change_text_colour(int colour);

#endif //PROJECT_COLOURS_H
